import Link from "next/link";
import "./globals.css";
import { Fugaz_One } from 'next/font/google';

const fugaz = Fugaz_One({ subsets: ["latin"], weight: ['400']});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const header = (
    <header className='p-6 flex justify-between '>
        <Link href="/">
        <h1 className={'text-xl textGradient ' + fugaz.className}> Broodl </h1>
        </Link>
        <h2 className={' ' + fugaz.className}>Placeholder</h2>
        
    </header>
  )

  const footer = (
    <footer className="grid place-items-center py-16">
      <p className={'text-indigo-400 ' + fugaz.className}>Made with ❤️</p>
    </footer>
  )



  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
