import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const header = (
    <header>
      <div style={{ display: 'flex', justifyContent: 'space-between'}}>
        <h1> Broodl </h1>
        <h2>placeholder</h2>
      </div>
    </header>
  )

  const footer = (
    <footer className="grid place-items-center">
      <p>footer</p>
    </footer>
  )



  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
